FIRST_LOGIN = "//*[@id='Login']/div/div/button[1]"

PASSWORD_FIELD = "password"
EMAIL_FIELD = "email"
BTN_NEXT = "btn-next"
LOGIN_BTN = "btnLogin"
CODE_BTN = "//input[@name='codeType' and @value='SMS']"
ONE_TIME_CODE_FIELD = "oneTimeCode"
SUBMIT_BTN = "btnSubmit"
VIEW_MODAL_CONTAINER = "view-modal-container"
REMOVE_CONTAINER_SCRIPT="""var element = arguments[0];element.parentNode.removeChild(element);"""
ICON_TRANSFER_BTN = "icon-transfer"
TRANSFER_MARKET_CONTAINER_BTN = "ut-tile-transfer-market"
SEARCHED_PLAYER_FIELD = "ut-text-input-control"
FIRST_RESULT_INPUT_SEARCH = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[1]/div/div/ul/button[1]"
MAX_BIN_PRICE_INPUT = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[6]/div[2]/input"
MIN_BIN_PRICE_INPUT = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[5]/div[2]/input"
SEARCH_PLAYER_BTN = "call-to-action"
BUY_BTN = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/button[2]"
CANCEL_BUY_BTN = "/html/body/div[4]/section/div/div/button[2]"
CONFIRM_BUY_BTN = "/html/body/div[4]/section/div/div/button[1]"
NAVIGATE_BACK = "ut-navigation-button-control"
INCREASE_PRICE_BTN="/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[6]/div[2]/button[2]"
DECREASE_PRICE_BTN="/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[5]/div[2]/button[2]"
NO_RESULTS_FOUND = "/html/body/main/section/section/div[2]/div/div/section/div/div[2]/div/span"
#SEND_TO_TRANSFER_BTN="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[3]/button[7]"
LIST_ON_TRANSFER_BTN="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[1]/button"
INCREASE_PRICE_AFTER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/button[2]"
DECREASE_PRICE_AFTER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/button[1]"
MIN_BIN_PRICE_INPUT_AFTER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/input"
MAX_BIN_PRICE_INPUT_AFTER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/input"
LIST_ITEM_ON_TRANSFER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/button"