QUALITY_FILTERS = ['Bronze', 'Silver', 'Gold', 'Special']
POSITIONS = ['Defenders', 'Midfielders', 'Attackers', 'GK', 'RWB', 'RB', 'CB', 'LB', 'LWB', 'CDM', 'RM', 'CM', 'LM', 'CAM', 'RF', 'CF', 'LF', 'RW', 'ST', 'LW']
CHEMISTRY_STYLES = ['BASIC', 'SNIPER', 'FINISHER', 'DEADEYE', 'MARKSMAN', 'HAWK', 'ARTIST', 'ARCHITECT', 'POWERHOUSE', 'MAESTRO', 'ENGINE', 'SENTINEL', 'GUARDIAN', 'GLADIATOR',
         'BACKBONE', 'ANCHOR', 'HUNTER', 'CATALYST', 'SHADOW', 'WALL', 'SHIELD', 'CAT', 'GLOVE', 'GK BASIC']
NATIONALITIES = ['', 'Argentina', 'Brazil', 'England', 'France', 'Germany', 'Netherlands', 'Italy', 'Portugal', 'Spain', 'Afghanist.', 'Albania', 'Algeria', 'Angola',
                 'Antigua B.', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bolivia', 'Bosnia-H.',
                 'Brazil', 'Bulgaria', 'Burk. Faso', 'Burundi', 'Cameroon', 'Canada', 'Cape Verde', 'CAR', 'Chad', 'Chile', 'China PR', 'Chinese Taipei', 'Colombia',
                 'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Rep.', 'Denmark', 'Dom. Rep.', 'DR Congo', 'E. Guinea', 'Ecuador', 'Egypt',
                 'El Salvad.', 'England', 'Eritrea', 'Estonia', 'Ethiopia', 'Faroe Isl.', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
                 'Gibraltar', 'Greece', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bis', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
                 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Korea DPR', 'Korea Rep.',
                 'Kosovo', 'Latvia', 'Lebanon', 'Liberia', 'Libya', 'Liechten.', 'Lithuania', 'Luxemburg', 'Macedonia', 'Madagascar', 'Malawi', 'Mali', 'Malta',
                 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'N. Ireland', 'N.Antilles', 'Namibia',
                 'Netherlands', 'New Caled.', 'New Zealand', 'Niger', 'Nigeria', 'Norway', 'Palestinian Authority', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
                 'Portugal', 'Puerto Rico', 'Romania', 'Russia', 'Rwanda', 'S. Africa', 'São Tomé & Príncipe', 'Saudi Ara.', 'Scotland', 'Senegal', 'Serbia', 'Sierra L.',
                 'Slovakia', 'Slovenia', 'South Sudan', 'Spain', 'St Kitts Nevis', 'St Lucia', 'Sudan', 'Suriname', 'Sweden', 'Switzerl.', 'Syria', 'Tanzania',
                 'Thailand', 'Togo', 'Trinidad', 'Tunisia', 'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates', 'Uruguay', 'USA', 'Uzbekistan', 'Venezuela', 'Vietnam',
                 'Wales', 'Zambia', 'Zimbabwe']
LEAGUES = ['Premier League (ENG 1)', 'EFL Championship (ENG 2)', 'EFL League One (ENG 3)', 'EFL League Two (ENG 4)', 'Ligue 1 Conforama (FRA 1)',
           'Domino’s Ligue 2 (FRA 2)', 'Serie A TIM (ITA 1)', 'Calcio B (ITA 2)', 'Bundesliga (GER 1)', 'Bundesliga 2 (GER 2)', '3. Liga (GER 3)',
           'LaLiga Santander (ESP 1)', 'LaLiga SmartBank (ESP 2)', '3F Superliga (DEN 1)', 'Allsvenskan (SWE 1)', 'Camp. AFP PlanVital (CHI 1)',
           'CONMEBOL Libertadores (LIB)', 'CONMEBOL Sudamericana (SUD)', 'CSL (CHN 1)', 'Eliteserien (NOR 1)', 'Eredivisie (NED 1)', 'Finnliiga (FIN 1)',
           'Hellas Liga (GRE 1)', 'Hyundai A-League (AUS 1)', 'Icons (ICN)', 'K-League 1 (KOR 1)', 'League of Russia (RUS 1)', 'LIGA BBVA MX (MEX 1)',
           'Liga Dimayor (COL 1)', 'Liga do Brasil (BRA 1)', 'Liga Hrvatska (CRO 1)', 'Liga I (ROM 1)', 'Liga NOS (POR 1)', 'MBS Pro League (SAU 1)',
           'Meiji Yasuda J1 (JPN 1)', "Men's National (INT)", 'MLS (MLS)', 'PKO Ekstraklasa (POL 1)', 'Pro League (BEL 1)', 'RSL (SUI 1)', 'SAF (ARG 1)',
           'Scottish Prem (SPFL)', 'South African FL (RSA 1)', 'SSE Airtricity Lge (IRL 1)', 'Süper Lig (TUR 1)', 'Ukrayina Liha (UKR 1)',
           'United Emirates League (UAE 1)', 'Ö. Bundesliga (AUT 1)', 'Česká Liga (CZE 1)']
CLUBS = ['1. FC Nürnberg', '1. FSV Mainz 05', '1860 München', 'Aalborg BK', 'Aarhus AGF', 'Aberdeen', 'Abha Club', 'AC Ajaccio', 'AC Horsens', 'Academica Clinceni',
         'Accrington', 'AD Alcorcón', 'Adelaide United', 'Admira Wacker', 'ADO Den Haag', 'AEK Athens', 'AFC Bournemouth', 'AFC Eskilstuna', 'AFC Wimbledon', 'AIK',
         'AJ Auxerre', 'Ajax', 'Al Adalah', 'Al Ahli', 'Al Ain FC', 'Al Faisaly', 'Al Fateh', 'Al Fayha', 'Al Hazem', 'Al Hilal', 'Al Ittihad', 'Al Nassr', 'Al Raed',
         'Al Shabab', 'Al Taawoun', 'Al Wehda', 'Al. Petrolera', 'Alanyaspor', 'Albacete BP', 'Aldosivi', 'Alianza Lima', 'Always Ready', 'América', 'América de Cali',
         'Amiens SC', 'Angers SCO', 'Antalyaspor', 'Aragua FC', 'Argentina', 'Argentinos Jrs.', 'Arka Gdynia', 'Arsenal', 'Arsenal', 'AS Monaco', 'Ascoli', 'ASSE',
         'Aston Villa', 'Astra Giurgiu', 'Atalanta', 'Athletic Club', 'Athletico-PR', 'Atl. Bucaramanga', 'Atl. Nacional', 'Atlanta United', 'Atlas',
         'Atlético de San Luis', 'Atlético Grau', 'Atlético Huila', 'Atlético Madrid', 'Atlético Mineiro', 'Atlético Tucumán', 'Aucas', 'Audax Italiano', 'Aue',
         'Austin FC', 'Australia', 'Austria', 'Avaí', 'AZ', 'Bahia', 'Banfield', 'Barnsley', 'Başakşehir', 'Beijing Guoan', 'Beijing Renhe', 'Belenenses', 'Belgium',
         'Benevento', 'Beşiktaş', 'Bielefeld', 'Binacional', 'Birmingham City', 'BK Häcken', 'Blackburn Rovers', 'Blackpool', 'Blooming', 'Boavista FC', 'Bochum',
         'Bohemian FC', 'Bolívar', 'Bolivia', 'Bologna', 'Bolton', 'Botafogo', 'Bradford City', 'Braunschweig', 'Brazil', 'Brentford', 'Brescia', 'Brighton',
         'Brisbane Roar', 'Bristol City', 'Bristol Rovers', 'Brøndby IF', 'BSC Young Boys', 'Buenos Aires', 'Bulgaria', 'Burnley', 'Burton Albion', 'Bury', 'C. Stabia',
         'CA Osasuna', 'Cádiz CF', 'Cagliari', 'Cambridge Utd', 'Cameroon', 'Canada', 'Caracas F.C.', 'Cardiff City', 'Carl Zeiss Jena', 'Carlisle United',
         'Çaykur Rizespor', 'CD Antofagasta', 'CD Cobresal', 'CD Leganés', 'CD Lugo', 'CD Mirandés', 'CD Numancia', "CD O'Higgins", 'CD Palestino', 'CD Tenerife',
         'CD Tondela', 'CD Viñazur', 'Ceará SC', 'Celtic', 'Central Coast', 'Central Córdoba', 'Cercle Brugge', 'Cerezo Osaka', 'CF Fuenlabrada', 'CFR 1907 Cluj',
         'Chamois FC', 'Chapecoense', 'Charlton Ath', 'Chelsea', 'Cheltenham Town', 'Chemnitzer FC', 'Chiavari', 'Chicago Fire', 'Chievo Verona', 'Chile', 'China PR',
         'Chindia', 'Chongqing SWM', 'Cittadella', 'Clermont Foot', 'Club Brugge', 'Club Nacional', 'Colchester', 'Colo-Colo', 'Colombia', 'Colón', 'Colorado Rapids',
         'Columbus Crew SC', 'Coquimbo Unido', 'Cork City', 'Cosenza', "Côte d'Ivoire", 'Coventry City', 'Cracovia', 'Crawley Town', 'Cremona', 'Crewe Alexandra',
         'Crotone', 'Cruz Azul', 'Cruzeiro', 'Crystal Palace', 'CS Emelec', 'CSA', 'CSKA Moscow', 'Cúcuta Deportivo', 'Curicó Unido', 'Cusco FC', 'Czech Republic',
         'D. Alavés', 'D.C. United', 'Daegu FC', 'Dalian Yifang', 'Damac FC', 'Darmstadt', 'Defensa', 'Delfín S.C.', 'Denizlispor', 'Denmark', 'Depor. Iquique',
         'Deportes Ñuñoa', 'Deportes Tolima', 'Deportivo Cali', 'Deportivo Pasto', 'Derby County', 'Derry City', 'Desportivo Aves', 'Dijon FCO', 'Dinamo Zagreb',
         'Djurgårdens IF', 'Doncaster', 'Dortmund', 'Dresden', 'Duisburg', 'Dundalk', 'Düsseldorf', 'Dynamo Kyiv', 'EA Guingamp', 'Ecuador', 'Egypt', 'El Nacional',
         'Elche CF', 'Empoli', 'England', 'Envigado', 'Esbjerg fB', 'Est. de Mérida', 'ESTAC Troyes', 'Estudiantes', 'Ettifaq FC', 'Everton', 'Everton de Viña',
         'Excel Mouscron', 'Exeter City', 'Extremadura UD', 'F.C. Tokyo', 'Falkenbergs FF', 'FBC Melgar', 'FC Augsburg', 'FC Barcelona', 'FC Basel 1893', 'FC Bayern',
         'FC Bayern II', 'FC Botoșani', 'FC Chambly', 'FC Cincinnati', 'FC Dallas', 'FC Dinamo 1948', 'FC Emmen', 'FC Famalicão', 'FC Groningen', 'FC Hermannstadt',
         'FC Juárez', 'FC København', 'FC Lorient', 'FC Lugano', 'FC Luzern', 'FC Metz', 'FC Midtjylland', 'FC Nantes', 'FC Nordsjælland', 'FC Porto', 'FC Seoul',
         'FC Sion', 'FC St. Gallen', 'FC Thun', 'FC Twente', 'FC Utrecht', 'FC Viitorul', 'FC Voluntari', 'FC Zürich', 'FCSB', 'FCSM', 'Fenerbahçe', 'Fénix', 'Feyenoord',
         'Finland', 'Finn Harps', 'Fiorentina', 'FK Austria Wien', 'FK Bodø/Glimt', 'FK Haugesund', 'Fleetwood Town', 'Fluminense', 'Forest Green', 'Fortaleza',
         'Fortuna Sittard', 'France', 'Frankfurt', 'Free Agents', 'Frosinone', 'FSV Zwickau', 'Fulham', 'Fürth', 'FUT Icons', 'Galatasaray', 'Gamba Osaka', 'Gangwon FC',
         'Gaz Metan Mediaș', 'Gazişehir Gaziantep', 'Gençlerbirliği', 'Genoa', 'Germany', 'Getafe CF', 'GIF Sundsvall', 'Gil Vicente', 'Gillingham', 'Gimnasia',
         'Girona FC', 'Girondins de Bx', 'Godoy Cruz', 'Goiás', 'Górnik Zabrze', 'Göztepe', 'Granada CF', 'Greece', 'Grêmio', 'Grenoble Foot', 'Grimsby Town',
         'Guadalajara', 'Guangzhou', 'Guangzhou R&F', 'Gyeongnam FC', 'H.Consa.Sapporo', 'Hallescher FC', 'Hamburg', 'Hamilton', 'Hammarby IF', 'Hannover 96',
         'Hansa Rostock', 'Havre AC', 'Hearts', 'Hebei CFFC', 'Heidenheim', 'Hellas Verona', 'Helsingborgs IF', 'Henan Jianye', 'Heracles Almelo', 'Hertha BSC',
         'Hibernian', 'HJK Helsinki', 'Hobro IK', 'Houston Dynamo', 'Huachipato FC', 'Huddersfield', 'Hull City', 'Hungary', 'Huracán', 'Iceland', 'IF Elfsborg',
         'IFK Göteborg', 'IFK Norrköping', 'IK Sirius', 'Impact Montréal', 'Incheon United', 'Indep. Medellín', 'Independiente', 'Independiente', 'India', 'Ingolstadt',
         'Inter', 'Inter Miami CF', 'Internacional', 'Ipswich', 'Ireland', 'Italy', 'Jagiellonia', 'Jaguares', 'Jeju United', 'Jeonbuk Hyundai', 'Jiangsu Suning',
         'Júbilo Iwata', 'Junior', 'KAA Gent', 'Kaiserslautern', 'Kaizer Chiefs', 'Kalmar FF', 'Karlsruher SC', 'KAS Eupen', 'Kashima Antlers', 'Kasimpaşa', 'Kawasaki-F',
         'Kayserispor', 'KFC Uerdingen', 'Kiel', 'Kilmarnock', 'Köln', 'Konyaspor', 'Korona Kielce', 'KRC Genk', 'Kristiansund', 'KV Kortrijk', 'KV Mechelen',
         'KV Oostende', 'La Berrichonne', 'La Equidad', 'LA Galaxy', 'La Spezia', 'LAFC', 'Lanús', 'LASK Linz', 'Lazio', 'LDU Quito', 'Le Mans FC', 'Lecce',
         'Lech Poznań', 'Lechia Gdańsk', 'Leeds United', 'Legia Warszawa', 'Leicester City', 'León', 'Levante UD', 'Leverkusen', 'Leyton Orient', 'Libertad',
         'Lillestrøm SK', 'Lincoln City', 'Liverpool', 'Liverpool', 'Livingston', 'Livorno', 'ŁKS Łódź', 'Llaneros', 'Lokomotiv Moscow', 'LOSC Lille', 'Luqueño',
         'Luton Town', 'Lyngby BK', "M'gladbach", 'Macclesfield', 'Magdeburg', 'Málaga CF', 'Malmö FF', 'Manchester City', 'Manchester Utd', 'Mansfield Town', 'Marítimo',
         'Matsumoto Yamaga', 'Melb. Victory', 'Melbourne City', 'Mexico', 'Middlesbrough', 'Milan', 'Millonarios', 'Millwall', 'Mineros', 'Minnesota United',
         'Mjøndalen IF', 'MK Dons', 'MKE Ankaragücü', 'Molde FK', 'Monarcas Morelia', 'Monterrey', 'Montpellier HSC', 'Morecambe', 'Moreirense FC', 'Motherwell',
         'Nacional', 'Nacional Potosí', 'Nagoya Grampus', 'Nancy', 'Napoli', 'Nashville SC', 'Necaxa', 'Netherlands', 'Neuchâtel Xamax', 'New England',
         'New York City FC', 'New Zealand', 'Newcastle Jets', 'Newcastle Utd', "Newell's", 'Newport County', 'Nîmes Olympique', 'Northampton', 'Northern Ireland',
         'Norway', 'Norwich', "Nott'm Forest", 'Núñez', 'NY Red Bulls', 'O. Petrolero', 'Odds BK', 'Odense BK', 'OGC Nice', 'Oita Trinita', 'OL', 'Oldham Athletic',
         'Olimpia', 'Olympiacos CFP', 'OM', 'Once Caldas', 'Örebro SK', 'Orlando City', 'Orlando Pirates', 'Östersunds FK', 'Oxford United', 'Pachuca', 'Paços Ferreira',
         'Paderborn', 'Panathinaikos', 'PAOK', 'Paraguay', 'Paris', 'Paris FC', 'Parma', 'Patriotas', 'Patronato', 'PEC Zwolle', 'Peñarol', 'Perth Glory', 'Peru',
         'Perugia', 'Pescara', 'Peterborough', 'Philadelphia', 'Piast Gliwice', 'Piemonte Calcio', 'Pisa', 'Plaza Colonia', 'Plymouth Argyle', 'Pogoń Szczecin',
         'Pohang Steelers', 'Poland', 'Politehnica Iași', 'Pordenone', 'Port Vale', 'Portimonense SC', 'Portland Timbers', 'Portsmouth', 'Portugal', 'Preston',
         'Preußen Münster', 'PSV', 'Puebla', 'QPR', 'Querétaro', 'R. Oviedo', 'R. Sporting', 'R. Valladolid CF', 'R. Zaragoza', 'Racing', 'Racing Club',
         'Raków Częstochowa', 'Randers FC', 'Rangers', 'Ranheim Fotball', 'Rayo Vallecano', 'RB Leipzig', 'RB Salzburg', 'RC Celta', 'RC Deportivo', 'RC Lens',
         'RC Strasbourg', 'RCD Espanyol', 'RCD Mallorca', 'Reading', 'Real Betis', 'Real Madrid', 'Real Salt Lake', 'Real Sociedad', 'Regensburg', 'Rio Ave FC',
         'Rionegro Águilas', 'River Plate', 'River Plate', 'RKC Waalwijk', 'Rochdale', 'Rodez AF', 'Roma', 'Romania', 'Rosario Central', 'Rosenborg BK', 'Ross County',
         'Rotherham Utd', 'Royal Antwerp FC', 'RSC Anderlecht', 'Russia', 'S-Hiroshima', 'S. Großaspach', 'Sagan Tosu', 'Salerno', 'Salford City', 'Sampdoria',
         'San Lorenzo', 'Sandhausen', 'Sangju Sangmu', 'Santa Clara', 'Santa Fe', 'Santos', 'Santos Laguna', 'Sarpsborg 08 FF', 'Sassuolo', 'SC Braga', 'SC Freiburg',
         'SC Heerenveen', 'Schalke', 'Scotland', 'SCR Altach', 'Scunthorpe Utd', 'SD Eibar', 'SD Huesca', 'SD Ponferradina', 'Seattle Sounders', 'Seongnam FC',
         'Sepsi OSK', 'Servette FC', 'Sevilla FC', 'Shakhtar Donetsk', 'Shamrock Rovers', 'Shandong Luneng', 'Shanghai Shenhua', 'Shanghai SIPG', 'Sheffield Utd',
         'Sheffield Wed', 'Shenzhen Kaisa', 'Shimizu S-Pulse', 'Shonan Bellmare', 'Shrewsbury', 'Silkeborg IF', 'Sint-Truiden', 'Sivasspor', 'SJ Earthquakes', 'SK Brann',
         'SK Rapid Wien', 'SK Sturm Graz', 'SKN St. Pölten', 'SL Benfica', 'Śląsk Wrocław', 'Slavia Praha', 'Sligo Rovers', 'Slovenia', 'SM Caen', 'Sol de América',
         'SønderjyskE', 'South Africa', 'Southampton', 'Southend United', 'Sp. Charleroi', 'Spain', 'SPAL', 'Sparta Praha', 'Sparta Rotterdam', 'Spartak Moscow',
         'Sport Huancayo', 'Sporting CP', 'Sporting KC', 'Spurs', 'St. Johnstone', 'St. Mirren', 'St. Pats', 'St. Pauli', 'Stabæk Fotball', 'Stade Brestois',
         'Stade de Reims', 'Stade Rennais', 'Standard Liège', 'Stevenage', 'Stoke City', 'Strømsgodset IF', 'Sunderland', 'Suwon Samsung', 'SV Mattersburg', 'SV Meppen',
         'SV Waldhof', 'Swansea City', 'Sweden', 'Swindon Town', 'Switzerland', 'Sydney FC', 'Talleres', 'Tianjin TEDA', 'Tianjin Tianhai', 'Tigre', 'Tigres', 'Tijuana',
         'Toluca', 'Torino', 'Toronto FC', 'Toulouse FC', 'Trabzonspor', 'Tranmere Rovers', 'Trapani', 'Tromsø IL', 'TSG Hoffenheim', 'TSV Hartberg', 'Turkey',
         'U. Católica', 'U.N.A.M.', 'UCD AFC', 'UD Almería', 'UD Las Palmas', 'Udinese', 'Ulsan Hyundai', 'Uni. Católica', 'Uni. Concepción', 'Unión', 'Union Berlin',
         'Unión Española', 'Unión La Calera', 'Unión Magdalena', 'United States', 'Univ. Craiova', 'Unterhaching', 'Urawa Reds', 'Uruguay', 'US Orléans', 'V. Guimarães',
         'V. Setúbal', 'Valencia CF', 'Valenciennes FC', 'Vålerenga Fotball', 'Vegalta Sendai', 'Vélez Sarsfield', 'Venezia', 'Venezuela', 'Veracruz', 'VfB Stuttgart',
         'VfL Osnabrück', 'VfL Wolfsburg', 'Viking FK', 'Viktoria Köln', 'Viktoria Plzeň', 'Villarreal CF', 'Vissel Kobe', 'Vitesse', 'VVV-Venlo', 'Waasl. Beveren',
         'Wales', 'Walsall', 'Waterford FC', 'Watford', 'Well. Phoenix', 'Werder Bremen', 'West Brom', 'West Ham', 'Western United', 'Whitecaps FC', 'Wiesbaden',
         'Wigan Athletic', 'Willem II', 'Wilstermann', 'Wisła Kraków', 'Wisła Płock', 'Wolfsberger AC', 'Wolves', 'WS Wanderers', 'WSG Tirol', 'Wuhan Zall', 'Würzburg',
         'Wycombe', 'Yeni Malatyaspor', 'Yokohama F･M', 'Zagłębie Lubin', 'Zamora FC', 'Zulte Waregem']
