FIRST_LOGIN = "//*[@id='Login']/div/div/button[1]"
PASSWORD_FIELD = "//*[@id='password']"
EMAIL_FIELD = "//*[@id='email']"
BTN_NEXT = "btn-next"
LOGIN_ENTER_APP="/html/body/main/div/div/div/button[1]"
LOGIN_BTN = "//*[@id='btnLogin']"
CODE_BTN = "//input[@name='codeType' and @value='SMS']"
ONE_TIME_CODE_FIELD = "//*[@id='oneTimeCode']"
VIEW_MODAL_CONTAINER = "view-modal-container"
ICON_TRANSFER_BTN = "icon-transfer"
TRANSFER_MARKET_CONTAINER_BTN = "ut-tile-transfer-market"
SCREEN_AFTER_LOADING = "/html/body/main/section[contains(@class,'game-navigation')]"
LOADER_ICON = "/html/body/div[4]/img"
SEARCHED_PLAYER_FIELD = "ut-text-input-control"
SEARCH_PRICE_HEADER = "search-price-header"
FIRST_RESULT_INPUT_SEARCH = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[1]/div/div/ul/button[1]"
MAX_BIN_PRICE_INPUT = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[6]/div[2]/input"
MIN_BIN_PRICE_INPUT = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[5]/div[2]/input"
SEARCH_PLAYER_BTN = "call-to-action"
NEXT_BUTTON = "/html/body/main/section/section/div[2]/div/div/section[1]/div/div/button[2]"
BUY_BTN = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/button[2]"
CANCEL_BUY_BTN = "/html/body/div[4]/section/div/div/button[2]"
CONFIRM_BUY_BTN = "/html/body/div[4]/section/div/div/button[1]"
NAVIGATE_BACK = "ut-navigation-button-control"
INCREASE_MIN_PRICE_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[5]/div[2]/button[2]"
DECREASE_MIN_PRICE_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[5]/div[2]/button[1]"
INCREASE_MAX_PRICE_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[6]/div[2]/button[2]"
DECREASE_MAX_PRICE_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[6]/div[2]/button[1]"
NO_RESULTS_FOUND = "/html/body/main/section/section/div[2]/div/div/section/div/div[2]/div/span"
SEND_TO_TRANSFER_BTN="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[3]/button[7]"
LIST_ON_TRANSFER_BTN="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[1]/button"
INCREASE_PRICE_AFTER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/button[2]"
DECREASE_PRICE_AFTER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/button[1]"
MIN_BIN_PRICE_INPUT_AFTER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/input"
MAX_BIN_PRICE_INPUT_AFTER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/input"
LIST_ITEM_ON_TRANSFER_LIST="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/button"
LOGIN_ERROR = "general-error"
CODE_ERROR = "origin-ux-textbox-status-message"
COIN_BALANCE = "view-navbar-currency-coins"
USER_NAME="/html/body/main/section/section/div[2]/div/div/div[1]/div/div[1]/div/h1"
SETTINGS_ICON_OPEN_WEB_APP= "/html/body/main/section/nav/button[8]"
SETTINGS_ICON_BLOCKED_WEB_APP = "/html/body/main/section/nav/button"
PLATFORM_ICON="/html/body/main/section/section/div[2]/div/div/div[1]/div/div[2]"
NEXT_PAGE="/html/body/main/section/section/div[2]/div/div/section[1]/div/div/button[2]"
GETTING_STARTED="/html/body/main/section/div/div/div/div[2]/div[2]"
LOGGED_ON_CONSOLE="ut-logged-on-console"
LOGIN_CAPTHA="ut-fun-captcha-required"
LOGIN_POPUP="ut-login-generic"
START_PLAYER_PRICE_ON_PAGE = "/html/body/main/section/section/div[2]/div/div/section[1]/div/ul/li["
END_PLAYER_PRICE_ON_PAGE ="]/div/div[2]/div[3]/span[2]"
BOUGHT_FOR="/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[1]/div[2]/div/span[2]"