FIRST_LOGIN = "//*[@id='Login']/div/div/button[1]"
PASSWORD_FIELD = "//*[@id='password']"
EMAIL_FIELD = "//*[@id='email']"
BTN_NEXT = "btn-next"
LOGIN_BTN = "btnLogin"
CODE_BTN = "//input[@name='codeType' and @value='SMS']"
ONE_TIME_CODE_FIELD = "//*[@id='oneTimeCode']"
VIEW_MODAL_CONTAINER = "view-modal-container"
ICON_TRANSFER_BTN = "icon-transfer"
TRANSFER_MARKET_CONTAINER_BTN = "ut-tile-transfer-market"
SCREEN_AFTER_LOADING = "/html/body/main/section[contains(@class,'game-navigation')]"
LOADER_ICON = "/html/body/div[4]/img"
SEARCHED_PLAYER_FIELD = "ut-text-input-control"
SEARCH_PRICE_HEADER = "search-price-header"
FIRST_RESULT_INPUT_SEARCH = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[1]/div/div/ul/button[1]"
MAX_BIN_PRICE_INPUT = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[6]/div[2]/input"
MIN_BIN_PRICE_INPUT = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[5]/div[2]/input"
SEARCH_ITEM_BTN = "call-to-action"
NEXT_BUTTON = "/html/body/main/section/section/div[2]/div/div/section[1]/div/div/button[2]"
BUY_BTN = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/button[2]"
CANCEL_BUY_BTN = "/html/body/div[4]/section/div/div/button[2]"
CONFIRM_BUY_BTN = "/html/body/div[4]/section/div/div/button[1]"
NAVIGATE_BACK = "ut-navigation-button-control"
INCREASE_MIN_PRICE_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[5]/div[2]/button[2]"
DECREASE_MIN_PRICE_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[5]/div[2]/button[1]"
INCREASE_MAX_PRICE_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[6]/div[2]/button[2]"
DECREASE_MAX_PRICE_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[2]/div[6]/div[2]/button[1]"
NO_RESULTS_FOUND = "/html/body/main/section/section/div[2]/div/div/section/div/div[2]/div/span"
SEND_TO_TRANSFER_BTN = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[3]/button[7]"
LIST_ON_TRANSFER_BTN = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[1]/button"
INCREASE_PRICE_AFTER_LIST = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/button[2]"
DECREASE_PRICE_AFTER_LIST = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/button[1]"
MIN_BIN_PRICE_INPUT_AFTER_LIST = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/input"
MAX_BIN_PRICE_INPUT_AFTER_LIST = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/input"
LIST_ITEM_ON_TRANSFER_LIST = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[2]/div[2]/button"
LOGIN_ERROR = "general-error"
CODE_ERROR = "origin-ux-textbox-status-message"
COIN_BALANCE = "view-navbar-currency-coins"
USER_NAME = "/html/body/main/section/section/div[2]/div/div/div[1]/div/div[1]/div/h1"
SETTINGS_ICON = "/html/body/main/section/nav/button[8]"
PLATFORM_ICON = "/html/body/main/section/section/div[2]/div/div/div[1]/div/div[2]"
NEXT_PAGE = "/html/body/main/section/section/div[2]/div/div/section[1]/div/div/button[2]"
GETTING_STARTED = "/html/body/main/section/div/div/div/div[2]/div[2]"
LOGGED_ON_CONSOLE = "ut-logged-on-console"
LOGIN_CAPTHA = "ut-fun-captcha-required"
SERVERS_DOWN = "ui-dialog-type-alert"
LOGIN_POPUP = "ut-login-generic"
START_ITEM_PRICE_ON_PAGE = "/html/body/main/section/section/div[2]/div/div/section[1]/div/ul/li["
END_ITEM_PRICE_ON_PAGE = "]/div/div[2]/div[3]/span[2]"
BOUGHT_FOR = "/html/body/main/section/section/div[2]/div/div/section[2]/div/div/div[2]/div[1]/div[2]/div/span[2]"

PLAYER_QUALITY_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[2]"
PLAYER_QUALITY_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[2]/div/ul"

PLAYER_POSITION_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[3]"
PLAYER_POSITION_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[3]/div/ul"

CHEM_STYLE_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[4]"
PLAYER_CHEM_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[4]/div/ul"

PLAYER_NATIONALITY_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[5]"
PLAYER_NATIONALITY_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[5]/div/ul"

PLAYER_LEAGUE_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[6]"
PLAYER_LEAGUE_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[6]/div/ul"

PLAYER_CLUB_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[7]"
PLAYER_CLUB_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[7]/div/ul"

CONSUMABLES_NAV_MENU_BTN = "/html/body/main/section/section/div[2]/div/div[1]/div/a[4]"

CONSUMABLE_TYPE_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[2]"
CONSUMABLE_TYPE_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[2]/div/ul"

CONSUMABLES_QUALITY_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[3]"
CONSUMABLES_QUALITY_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[3]/div/ul"

CONSUMABLE_SPECIFIC_NAME_FILTER_BTN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[4]"
CONSUMABLE_SPECIFIC_NAME_FILTER_DROPDOWN = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[4]/div/ul"

PLAYERS_TAB_BUTTON = "/html/body/main/section/section/div[2]/div/div[1]/div/a[1]"
CONSUMABLES_TAB_BUTTON = "/html/body/main/section/section/div[2]/div/div[1]/div/a[4]"

RESET_QUALITY_FILTER_X = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[2]/div/div/button"
RESET_CHEM_STYLE_X = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[4]/div/div/button"

RESET_CONUMABLES_QUALITY_FILTER_X = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[3]/div/div/button"
RESET_PLAYER_NAME_X = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[1]/div/button"
REST_PLAYER_POSITION_X = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[3]/div/div/button"
RESET_PLAYER_NATION_X = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[5]/div/div/button"
RESET_PLAYER_LEAGUE_X = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[6]/div/div/button"
RESET_PLAYER_CLUB_X = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[7]/div/div/button"
PLAYER_NAME_PLACEHOLDER = "/html/body/main/section/section/div[2]/div/div[2]/div/div[1]/div[1]/div[1]"
LOGIN_MESSAGE = "tfa-login-panel-container-style"

RESET_FILTERS_BUTTON="/html/body/main/section/section/div[2]/div/div[2]/div/div[2]/button[1]"


